# Generated by Django 4.1.2 on 2026-04-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinanceListModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dn_code", models.CharField(max_length=255, verbose_name="DN Code")),
                (
                    "orderitem_id",
                    models.CharField(
                        default="",
                        max_length=255,
                        unique=True,
                        verbose_name="OrderItem ID",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Account Name"
                    ),
                ),
                (
                    "goods_code",
                    models.CharField(max_length=255, verbose_name="Goods Code"),
                ),
                (
                    "goods_desc",
                    models.CharField(
                        default="", max_length=255, verbose_name="Goods Code"
                    ),
                ),
                (
                    "shipped_qty",
                    models.BigIntegerField(default=0, verbose_name="Shipped QTY"),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Selling price"
                    ),
                ),
                (
                    "btw_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="BTW Cost"
                    ),
                ),
                (
                    "bol_commission",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Bol Commission"
                    ),
                ),
                (
                    "logistic_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Logistic Cost"
                    ),
                ),
                (
                    "product_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Product Cost"
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Product Cost",
                    ),
                ),
                (
                    "openid",
                    models.CharField(default="", max_length=255, verbose_name="Openid"),
                ),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "returned",
                    models.BooleanField(default=False, verbose_name="whether returned"),
                ),
                (
                    "selling_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Selling Date"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance Table",
                "verbose_name_plural": "Finance Table",
                "db_table": "financetable",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TransportationFeeListModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "send_city",
                    models.CharField(max_length=255, verbose_name="Send City"),
                ),
                (
                    "receiver_city",
                    models.CharField(max_length=255, verbose_name="Receiver City"),
                ),
                ("weight_fee", models.FloatField(default=0, verbose_name="Weight Fee")),
                ("volume_fee", models.FloatField(default=0, verbose_name="Volume Fee")),
                (
                    "min_payment",
                    models.FloatField(default=0, verbose_name="Min Payment"),
                ),
                (
                    "transportation_supplier",
                    models.CharField(
                        max_length=255, verbose_name="Transportation Supplier"
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who Created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Transportation Fee",
                "verbose_name_plural": "Transportation Fee",
                "db_table": "transportationfee",
                "ordering": ["-id"],
            },
        ),
    ]
